/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as GroupIdIndexRouteImport } from './routes/group.$id/index'
import { Route as GroupIdSettleRouteImport } from './routes/group.$id/settle'
import { Route as GroupIdSettingsRouteImport } from './routes/group.$id/settings'
import { Route as GroupIdAddRouteImport } from './routes/group.$id/add'
import { Route as GroupIdExpenseExpenseIdRouteImport } from './routes/group.$id/expense.$expenseId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIdIndexRoute = GroupIdIndexRouteImport.update({
  id: '/group/$id/',
  path: '/group/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIdSettleRoute = GroupIdSettleRouteImport.update({
  id: '/group/$id/settle',
  path: '/group/$id/settle',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIdSettingsRoute = GroupIdSettingsRouteImport.update({
  id: '/group/$id/settings',
  path: '/group/$id/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIdAddRoute = GroupIdAddRouteImport.update({
  id: '/group/$id/add',
  path: '/group/$id/add',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIdExpenseExpenseIdRoute = GroupIdExpenseExpenseIdRouteImport.update({
  id: '/group/$id/expense/$expenseId',
  path: '/group/$id/expense/$expenseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/profile': typeof ProfileRoute
  '/invite/$token': typeof InviteTokenRoute
  '/group/$id/add': typeof GroupIdAddRoute
  '/group/$id/settings': typeof GroupIdSettingsRoute
  '/group/$id/settle': typeof GroupIdSettleRoute
  '/group/$id/': typeof GroupIdIndexRoute
  '/group/$id/expense/$expenseId': typeof GroupIdExpenseExpenseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/profile': typeof ProfileRoute
  '/invite/$token': typeof InviteTokenRoute
  '/group/$id/add': typeof GroupIdAddRoute
  '/group/$id/settings': typeof GroupIdSettingsRoute
  '/group/$id/settle': typeof GroupIdSettleRoute
  '/group/$id': typeof GroupIdIndexRoute
  '/group/$id/expense/$expenseId': typeof GroupIdExpenseExpenseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/profile': typeof ProfileRoute
  '/invite/$token': typeof InviteTokenRoute
  '/group/$id/add': typeof GroupIdAddRoute
  '/group/$id/settings': typeof GroupIdSettingsRoute
  '/group/$id/settle': typeof GroupIdSettleRoute
  '/group/$id/': typeof GroupIdIndexRoute
  '/group/$id/expense/$expenseId': typeof GroupIdExpenseExpenseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/overview'
    | '/profile'
    | '/invite/$token'
    | '/group/$id/add'
    | '/group/$id/settings'
    | '/group/$id/settle'
    | '/group/$id/'
    | '/group/$id/expense/$expenseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/overview'
    | '/profile'
    | '/invite/$token'
    | '/group/$id/add'
    | '/group/$id/settings'
    | '/group/$id/settle'
    | '/group/$id'
    | '/group/$id/expense/$expenseId'
  id:
    | '__root__'
    | '/'
    | '/overview'
    | '/profile'
    | '/invite/$token'
    | '/group/$id/add'
    | '/group/$id/settings'
    | '/group/$id/settle'
    | '/group/$id/'
    | '/group/$id/expense/$expenseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OverviewRoute: typeof OverviewRoute
  ProfileRoute: typeof ProfileRoute
  InviteTokenRoute: typeof InviteTokenRoute
  GroupIdAddRoute: typeof GroupIdAddRoute
  GroupIdSettingsRoute: typeof GroupIdSettingsRoute
  GroupIdSettleRoute: typeof GroupIdSettleRoute
  GroupIdIndexRoute: typeof GroupIdIndexRoute
  GroupIdExpenseExpenseIdRoute: typeof GroupIdExpenseExpenseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$id/': {
      id: '/group/$id/'
      path: '/group/$id'
      fullPath: '/group/$id/'
      preLoaderRoute: typeof GroupIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$id/settle': {
      id: '/group/$id/settle'
      path: '/group/$id/settle'
      fullPath: '/group/$id/settle'
      preLoaderRoute: typeof GroupIdSettleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$id/settings': {
      id: '/group/$id/settings'
      path: '/group/$id/settings'
      fullPath: '/group/$id/settings'
      preLoaderRoute: typeof GroupIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$id/add': {
      id: '/group/$id/add'
      path: '/group/$id/add'
      fullPath: '/group/$id/add'
      preLoaderRoute: typeof GroupIdAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$id/expense/$expenseId': {
      id: '/group/$id/expense/$expenseId'
      path: '/group/$id/expense/$expenseId'
      fullPath: '/group/$id/expense/$expenseId'
      preLoaderRoute: typeof GroupIdExpenseExpenseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OverviewRoute: OverviewRoute,
  ProfileRoute: ProfileRoute,
  InviteTokenRoute: InviteTokenRoute,
  GroupIdAddRoute: GroupIdAddRoute,
  GroupIdSettingsRoute: GroupIdSettingsRoute,
  GroupIdSettleRoute: GroupIdSettleRoute,
  GroupIdIndexRoute: GroupIdIndexRoute,
  GroupIdExpenseExpenseIdRoute: GroupIdExpenseExpenseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
