/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ExpenseIdRouteImport } from './routes/expense.$id'
import { Route as GroupIdIndexRouteImport } from './routes/group.$id/index'
import { Route as GroupIdAddRouteImport } from './routes/group.$id/add'

const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseIdRoute = ExpenseIdRouteImport.update({
  id: '/expense/$id',
  path: '/expense/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIdIndexRoute = GroupIdIndexRouteImport.update({
  id: '/group/$id/',
  path: '/group/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIdAddRoute = GroupIdAddRouteImport.update({
  id: '/group/$id/add',
  path: '/group/$id/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/expense/$id': typeof ExpenseIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/group/$id/add': typeof GroupIdAddRoute
  '/group/$id/': typeof GroupIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/expense/$id': typeof ExpenseIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/group/$id/add': typeof GroupIdAddRoute
  '/group/$id': typeof GroupIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/expense/$id': typeof ExpenseIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/group/$id/add': typeof GroupIdAddRoute
  '/group/$id/': typeof GroupIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/overview'
    | '/expense/$id'
    | '/invite/$token'
    | '/group/$id/add'
    | '/group/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/overview'
    | '/expense/$id'
    | '/invite/$token'
    | '/group/$id/add'
    | '/group/$id'
  id:
    | '__root__'
    | '/'
    | '/overview'
    | '/expense/$id'
    | '/invite/$token'
    | '/group/$id/add'
    | '/group/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OverviewRoute: typeof OverviewRoute
  ExpenseIdRoute: typeof ExpenseIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  GroupIdAddRoute: typeof GroupIdAddRoute
  GroupIdIndexRoute: typeof GroupIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense/$id': {
      id: '/expense/$id'
      path: '/expense/$id'
      fullPath: '/expense/$id'
      preLoaderRoute: typeof ExpenseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$id/': {
      id: '/group/$id/'
      path: '/group/$id'
      fullPath: '/group/$id/'
      preLoaderRoute: typeof GroupIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$id/add': {
      id: '/group/$id/add'
      path: '/group/$id/add'
      fullPath: '/group/$id/add'
      preLoaderRoute: typeof GroupIdAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OverviewRoute: OverviewRoute,
  ExpenseIdRoute: ExpenseIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  GroupIdAddRoute: GroupIdAddRoute,
  GroupIdIndexRoute: GroupIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
